* Second version

** Referee report 

This is in [[file:./ref-report.txt]]

** Reply to referee

Text is a markdown document: [[file:./ref-reply.md]]

** Dealing with the referee's points

1. [-] Representative spectra or color-scale PV image
   - A 1D spectrum could be used to address points 5 and 8
2. [-] Slit labelling - collision with axis labelling 
   - [X] Change to lower case letters for slits in Fig 2
   - [ ] Same for other figures
   - [ ] Update text
3. [X] Better indicate axis direction on figures
4. [ ] Proper motion nitpicks
5. [ ] More details on how velocities are derived
6. [ ] Discrepancy in axis ratio of inner shell?
7. [ ] Velocity gradients versus amplitudes
   - Michael was right!
8. [ ] Last sentence of section 4.2
   - Referee has doubt how we can find a velocity difference between diffuse and compact component
   - The answer is that [O III] is only more "diffuse" at HST resolution. At arcsecond scales it is compact.
9. [ ] More discussion on knot complexes
10. [ ] Can we rule out a brief ejection event?
11. [ ] Older lobes that have faded?


** Detailed log of changes

*** DONE Move Affinity Designer files to this repo
CLOSED: [2020-10-03 Sat 16:57]
+ I now have Affinity Designer installed on the iPad [2020-08-24 Mon] but the entire ~teresa-turtle~ repo is too large to sync with Working Copy
+ So, I will just copy all the ~.afdesign~ files into this repo on the MacMini and sync that via github


**** Find which figure files have associated .afdesign files and copy them into this project

+ /Do not run this script again/ like *EVER* - since it will overwrite the edited ~.afdesign~ files
#+begin_src sh :results verbatim :eval no
  files=$(grep 'Graphic file' ms.log | cut -d ' ' -f2 | grep "^figs/" | sed -e 's/-lores//' | cut -d '.' -f1)
  for f in $files; do
      if [[ -f ../Teresa-Turtle/$f.afdesign ]]; then
          # ls -l ../Teresa-Turtle/$f.afdesign
          cp -v ../Teresa-Turtle/$f.afdesign figs
      fi
  done
#+end_src

#+RESULTS:
#+begin_example
../Teresa-Turtle/figs/turtle-overview.afdesign -> figs/turtle-overview.afdesign
../Teresa-Turtle/figs/turtle-halo-slit-x.afdesign -> figs/turtle-halo-slit-x.afdesign
../Teresa-Turtle/figs/turtle-peanut-map.afdesign -> figs/turtle-peanut-map.afdesign
../Teresa-Turtle/figs/turtle-heii-shell-components.afdesign -> figs/turtle-heii-shell-components.afdesign
../Teresa-Turtle/figs/turtle-knot-complex-map.afdesign -> figs/turtle-knot-complex-map.afdesign
../Teresa-Turtle/figs/turtle-lobes-simplified-components.afdesign -> figs/turtle-lobes-simplified-components.afdesign
../Teresa-Turtle/figs/turtle-halo-map.afdesign -> figs/turtle-halo-map.afdesign
../Teresa-Turtle/figs/turtle-shell-velocity-axes-annotated.afdesign -> figs/turtle-shell-velocity-axes-annotated.afdesign
../Teresa-Turtle/figs/turtle-heii-shell-annotated.afdesign -> figs/turtle-heii-shell-annotated.afdesign
../Teresa-Turtle/figs/turtle-heii-shell-velocity-axes-annotated.afdesign -> figs/turtle-heii-shell-velocity-axes-annotated.afdesign
../Teresa-Turtle/figs/turtle-nii-knot-complexes.afdesign -> figs/turtle-nii-knot-complexes.afdesign
../Teresa-Turtle/figs/turtle-knot-complexes-velocity-axes-annotated.afdesign -> figs/turtle-knot-complexes-velocity-axes-annotated.afdesign
../Teresa-Turtle/figs/turtle-lobes-simplified-systems.afdesign -> figs/turtle-lobes-simplified-systems.afdesign
../Teresa-Turtle/figs/cut-axis-4panel.afdesign -> figs/cut-axis-4panel.afdesign
../Teresa-Turtle/figs/vel-radius-systems-annotated.afdesign -> figs/vel-radius-systems-annotated.afdesign
../Teresa-Turtle/figs/turtle-flow-axis-history.afdesign -> figs/turtle-flow-axis-history.afdesign
../Teresa-Turtle/figs/turtle-density-profile.afdesign -> figs/turtle-density-profile.afdesign
../Teresa-Turtle/figs/mass-loss-history-annotated.afdesign -> figs/mass-loss-history-annotated.afdesign
../Teresa-Turtle/figs/hr-pne-annotated.afdesign -> figs/hr-pne-annotated.afdesign
../Teresa-Turtle/figs/cousins-of-the-turtle.afdesign -> figs/cousins-of-the-turtle.afdesign
../Teresa-Turtle/figs/turtle-density-calibration.afdesign -> figs/turtle-density-calibration.afdesign
../Teresa-Turtle/figs/line-ratios-vs-ion-parameter.afdesign -> figs/line-ratios-vs-ion-parameter.afdesign
#+end_example



* First version
** Reduce file size
[2020-07-20 Mon]
+ Initial rejection because of PDF being too large (>10 MB)
*** Make lores versions of some figures
+ ~figs/cousins-of-the-turtle-lores.pdf~
  + spectacular reduction using "Reduce file size" quartz filter in Preview export
+ ~figs/{oiii,nii}-propermotions.jpg~
  + reduce quality in export jpg settings in Preview
+ ~figs/*-map.pdf~
  + export as jpg at 150 dpi and lowest quality
*** Check file sizes of included figures
#+begin_src sh
  grep 'Graphic file' ms.log | cut -d ' ' -f2 |xargs du -sk |sort -nr
#+end_src

#+RESULTS:
| 2112 | figs/oiii-propermotions-lores.jpg                      |
|  832 | figs/turtle-lobes-simplified-components-lores.jpg      |
|  832 | figs/nii-propermotions-lores.jpg                       |
|  792 | figs/turtle-lobes-simplified-systems.pdf               |
|  776 | figs/turtle-overview.pdf                               |
|  740 | figs/turtle-halo-slit-x.pdf                            |
|  544 | figs/turtle-halo-map-lores.jpg                         |
|  532 | figs/cut-axis-4panel.pdf                               |
|  392 | figs/turtle-heii-shell-components.pdf                  |
|  364 | tere-figs/Figure3.pdf                                  |
|  364 | figs/turtle-nii-knot-complexes.pdf                     |
|  224 | figs/turtle-peanut-map-lores.jpg                       |
|  180 | figs/cousins-of-the-turtle-lores.pdf                   |
|  176 | figs/turtle-knot-complex-map-lores.jpg                 |
|   76 | figs/turtle-knot-complexes-velocity-axes-annotated.pdf |
|   76 | figs/line-ratios-vs-ion-parameter.pdf                  |
|   68 | figs/turtle-heii-shell-annotated.pdf                   |
|   48 | tere-figs/Figure2a.pdf                                 |
|   48 | figs/vel-radius-systems-annotated.pdf                  |
|   48 | figs/turtle-shell-velocity-axes-annotated.pdf          |
|   44 | figs/hr-pne-annotated.pdf                              |
|   40 | figs/mass-loss-history-annotated.pdf                   |
|   32 | figs/turtle-density-profile.pdf                        |
|   32 | figs/turtle-density-calibration.pdf                    |
|   28 | figs/turtle-flow-axis-history.pdf                      |
|   24 | figs/turtle-heii-shell-velocity-axes-annotated.pdf     |
|   20 | figs/turtle-inclination-histogram.pdf                  |
